#! vim: ft=yaml ts=2:
---

- name: packages are installed
  package:
    name:
      - fontconfig
      - dejavu-sans-fonts
      - jenkins
    state: present

- name: jenkins is running
  service:
    name: jenkins
    state: started

# manual steps at this point
#
# unlock jenkins
# install plugins
# create user
# disable JNLP3
